application: nick-dirienzo
version: 2
runtime: python
api_version: 1

handlers:
- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/scripts
  static_dir: static/scripts

- url: /.*
  script: main.py
